# Generated by Django 4.2.11 on 2024-05-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qID', models.IntegerField()),
                ('ansCand', models.IntegerField()),
                ('ansStr', models.CharField(max_length=1200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qID', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('rating', models.BooleanField()),
            ],
        ),
    ]
